### ISSUE TITLE
winfacts fails with chomp errors and framedyn.dll popups

### ISSUE THREAD

**Issue by KlavsKlavsen** [adenning/winfacts#1]
I just installed winfacts module – and a few facts, creates an error, and makes windows (when puppet is run by hand) pop up a message about framedyn.dll missing – on windows 2003.

I attached screenshot of the error.
![puppet-facter-windows-winfacts-bug](https://f.cloud.github.com/assets/2737885/275265/23c11310-9083-11e2-8639-77f4ebac04c3.png)

I don't know if this is a generic facter issue? I also created 
https://projects.puppetlabs.com/issues/19746

**Comment by adenning** [comment]
Closing, wasn't a winfacts issue.
